### ISSUE TITLE
nutrient adequacy ratio 

### ISSUE THREAD

**Issue by meiyinghuang** [andrawis97/Hacking-Food---Team-Harvey-Willey#12]
Under the nutrient section, I saw you are trying to use the "nutrient adequacy ratio(NAR)" but I was not able to find the calculation processes of the "nutrient adequacy ratio". Could you share your steps? :)

Would recommend you to use the formula of the  NAR: individual’s intake of a nutrient as a % of the corresponding recommended allowance for that nutrient.

**Comment by glowang** [comment]
def nutrient_adequacy_ratio(x,p):
    return nutrient_demand(x,p)/hh_rda  #vector of total nutrients divide by minimum household rda(nutrition req)
#if more than one, adequate. # if less than one, not adequate.
nutrient_adequacy_ratio(x,p)*1000000

This is included in our code! It was embedded in some previous section :)

**Comment by glowang** [comment]
def nutrient_demand(x,p):
    c = r.demands(x,p)
    fct0,c0 = fct.align(c,axis=0,join='inner')
    N = fct0.T@c0

    return N 


here is the other function!
