### ISSUE TITLE
Explanation in code not consistent with graph

### ISSUE THREAD

**Issue by jnuesca** [andrawis97/Hacking-Food---Team-Harvey-Willey#13]
![Messages Image(4230416157)](https://user-images.githubusercontent.com/24834103/57046298-dcc48580-6c24-11e9-88f6-9d4b50cb528f.png)

Comment says "as price increases, nutritional outcome decreases", however graph looks to be at a constant level as price increases. Not sure if my interpretation is wrong, but if you could provide more comments to explain how to look at this, that would be helpful!

I think it could be due to the values along the X axis. Price ranges from 0.1 to 13000 but the current market price is 0.75. At a price of 13000, quantity demanded for mangoes is near 0, which might explain your large negative values on the Y axis.

**Comment by clairevparkinson** [comment]
Apologies for this. The comment was leftover from the professor's code on the Indian ICRISAT data. As per our presentation, we saw that nutritional outcomes did not change as price did. Changing the scale is a good idea though, we will try that out. Thank you for the suggestion!
