### ISSUE TITLE
Units of measurement (prices & quantities demanded)

### ISSUE THREAD

**Issue by jnuesca** [andrawis97/Hacking-Food---Team-Harvey-Willey#6]
Unclear what the unit of measurement is for price. 2600 TZS for how many units of beef? Same goes for quantities demanded (e.g. 0.069 units of beef, _does this necessarily make sense? Might need to change your budget constraint or standardize your units._

**Comment by clairevparkinson** [comment]
Prices for all of the Tanzanian data are in kilograms or in standard units for items such as coconuts according to Professor Ligon, although he said its possible there are errors in his code when he standardized the units.
