### ISSUE TITLE
np.linspace(0.1, 10, 500) not applicable to all goods in demand curve code block

### ISSUE THREAD

**Issue by jnuesca** [andrawis97/Hacking-Food---Team-Harvey-Willey#7]
np.linspace arguments are lower bound, upper bound, number of samples. From my understanding, this code generates an array of prices to graph quantities demanded for particular goods. However, prices (0.1 to 10) are don't map directly to the prices of goods you are attempting to graph.

For example: Goat Meat is 2000 TZS but is not included within the the price array.

**Comment by andrawis97** [comment]
Great Comment, thanks! will let you know when edits are made

**Comment by clairevparkinson** [comment]
We changed the arguments in np.linspace to cover the entire range of prices (np.linspace(0.5, 2600, 500)) to fix this issue, thanks!
