### ISSUE TITLE
Long Runtime Issue

### ISSUE THREAD

**Issue by nathanorwig** [andrawis97/Hacking-Food---Team-Harvey-Willey#8]
This portion of code has been running for 10+ minutes for me and a group member. Unsure if this was just an issue for us or if something underlying bug.
<img width="757" alt="Screen Shot 2019-05-01 at 3 08 00 PM" src="https://user-images.githubusercontent.com/35481199/57045621-041a5300-6c23-11e9-8c15-f1d2672a8b78.png">

**Comment by jnuesca** [comment]
Unable to run this as well!

**Comment by andrawis97** [comment]
Thanks Nathan and Josh, I've went ahead and put a warning message to make users aware of the run-time. This was a strategic decision, where we made a trade off between run time and the insights we harvested from the comprehensive graph we got.
