### ISSUE TITLE
Nutritional Outcome - conflict

### ISSUE THREAD

**Issue by meiyinghuang** [andrawis97/Hacking-Food---Team-Harvey-Willey#9]
Under the nutritional outcome section, the explanation shows me that "as price increases, nutritional outcome decreases. " However, that wasn't what the graph says. :)

**Comment by clairevparkinson** [comment]
Apologies for this. The comment was leftover from the professor's code on the Indian ICRISAT data. As per our presentation, we saw that nutritional outcomes did not change as price did. Thank you for catching that!

**Comment by andrawis97** [comment]
check out this [question!](https://github.com/andrawis97/Hacking-Food---Team-Harvey-Willey/issues/13)
